[package]
name = "automail"
version = "0.1.0"
authors = ["Tim Münster <muenster.tim@dismail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
