[package]
name = "automail"
version = "0.1.0"
authors = ["Tim Münster <tim.muenster@sap.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
